#!/bin/bash

cd ${OPENSHIFT_REPO_DIR}

echo -e  "<settings>\n   <localRepository>$OPENSHIFT_DATA_DIR</localRepository>\n</settings>\n" > $OPENSHIFT_DATA_DIR/settings.xml

mvn package -s $OPENSHIFT_DATA_DIR/settings.xml -DskipTests=true
